docs/rfc/0000-template.md, docs/rfc/0001-control-api.md
Resolves #4 
Разрабатываемое API должно конфигурироваться так, чтобы покрыть все use-case'ы которые мы сможем придумать.
Use cases:
1. P2P WebRTC  1 => 1
2. P2P WebRTC  1 <=> 1
3. Relayed WebRTC 1 => 1
4. Relayed WebRTC 1 <=> 1
5. Relayed WebRTC 2 <=> 2 
6. 1 WebRTC => 1 HLS, 1 WebRTC
7. 1 WebRTC => 1 WebRTC, 1 File Record
8. 1 File Record => 1 HLS
9. 1 WebRTC => 1 Preview(JPEGS list)
TODO: add endpoints config, callbacks config
-----------------------------------
[Rendered](https://github.com/instrumentisto/medea/blob/4-control-api-proto-spec/docs/rfc/0001-control-api.md)
=> RFC: Control API

docs/rfc/0002-webrc-client-api.md, signaling_test.html, src/api/client/rpc_connection.rs, src/api/protocol.rs, src/conf/mod.rs, src/signalling/room.rs
В текущей реализации, ICE кандидаты в `Event(IceCandidateDiscovered)` и `Command(SetIceCandidates)` хранятся в сериализованном виде. Дабы избежать лишних сериализаций/десериализаций/валидаций на стороне клиента, предлагается передавать кандидатов в трех полях. 
Было:
```rust
struct IceCandidateDiscovered {
peer_id: u64,
candidate: IceCandidate,
}
```
```json
{
"event": "IceCandidateDiscovered",
"data": {
"peer_id": 1,
"candidate": "user2_ice_candidate"
}
}
```
Стало:
```rust
struct IceCandidateDiscovered {
peer_id: u64,
candidate: IceCandidate,
}
struct IceCandidate {
candidate: String,
sdp_m_line_index: Option<u16>,
sdp_mid: Option<String>,
}
```
```json
{
"event": "IceCandidateDiscovered",
"data": {
"peer_id": 1,
"candidate": {
"candidate": "user2_ice_candidate",
"sdp_m_line_index": 0, …
```
=> Decompose IceCandidate

config.toml, src/api/client/server.rs, src/shutdown.rs, src/signalling/room.rs
Resolves #29 
1. Wrong default shutdown.timeout config.toml
2. Handler<OsSignal> for GracefulShutdown do not send messages to sub
- Created PR:
=> Fix OsSignal for GracefulShutdown, fix default shutdown.timeout in docs

.dockerignore, Dockerfile, Makefile
Part of #27 
Required for #33 
We need to add caching of dependencies in Medea Dockerfile.
Add building of Medea's deps in separate steps of Dockerfile.
- Created PR:
=> Improve Medea's Dockerfile to cache built dependencies

jason/demo/index.html, jason/e2e-demo/js/index.js, src/signalling/participants.rs, src/turn/repo.rs, src/turn/service.rs
Part of #77  
#80 was more of an raw upgrade, now its time to refactor to use `async fn` as much as possible. Starting with everything in medea::turn::*.
- Created PR:
=> Refactor turn::* package to more idiomatic async/.await (#77)

Cargo.lock, jason/src/rpc/mod.rs, proto/client-api/src/lib.rs
1. Open demo (`jason/demo`) app on a remote host.
2. Join to some `Room`.
3. Physically break connection with remote host (pull out the patch cord, e.g.).
Status of RPC connection will be `Connected`, but it's not. After some time, reconnection process may start, but it will be too late.
Status of RPC connection should change to `Reconnecting` and remain so until the connection is restored.
This bug is caused by the fact that in some cases the state of the entity reflecting the RPC connection is out of sync with the real state. Thus, the state remains in the `Open` state. The connection logic of `WebSocketRpcClient` implies that when the connection state is already `Open`, no need to do anything and `Promise` will be resolved instantly without reconnection try.
Add RPC connection state …
=> Fix Jason reconnection bug

jason/demo/chart/medea-demo/Chart.yaml, jason/demo/chart/medea-demo/conf/nginx.vh.conf, jason/demo/staging.vals.yaml
Part of #27
Set `Cache-Control: must-revalidate` header in the `demo`.
- Created PR:
=> Update demo Nginx config (#27)

Cargo.lock, src/media/mod.rs, src/media/peer.rs, src/signalling/elements/endpoints/mod.rs, src/signalling/elements/endpoints/webrtc/play_endpoint.rs, src/signalling/elements/endpoints/webrtc/publish_endpoint.rs, src/signalling/peers/metrics.rs, src/signalling/peers/mod.rs, src/signalling/room/command_handler.rs, src/signalling/room/mod.rs, src/signalling/room/rpc_server.rs
Part of #27
Required for #105
`PeersService` currently returns `ActorFuture`s (for the `Room` actor) from the functions and does changes before `ActorFuture` is actually polled. Also, because of it `Room` structure has public field `peer`. After this PR all this problems will be resolved.
Get rid of the `ActorFuture` and make this functions `async`.
- Created PR:
=> Refactor PeersService to more idiomatic async/.await (#27)

.clippy.toml, Cargo.lock, jason/src/rpc/heartbeat.rs, jason/src/rpc/mod.rs, jason/tests/api/room.rs, jason/tests/peer/mod.rs, jason/tests/rpc/mod.rs, proto/client-api/CHANGELOG.md, proto/client-api/src/lib.rs, proto/client-api/src/stats.rs, src/api/client/session.rs, tests/e2e/signalling/mod.rs, tests/e2e/signalling/rpc_settings.rs
Jason uses [wasm-bindgen] to interop with JS, and exposing 64 bit types to JS will make [wasm-bindgen] to use [BigInt64Array] / [BigUint64Array] in its JS glue, which is not implemented or was implemented too recently in some UA's.
E.g. it just breaks Safari, since WebKit doesnt have [BigInt64Array] / [BigUint64Array] support. https://bugs.webkit.org/show_bug.cgi?id=190800
[wasm-bindgen]: https://github.com/rustwasm/wasm-bindgen
[BigInt64Array]: https://tinyurl.com/y8bacb93
[BigUint64Array]: https://tinyurl.com/y4j3b4cs
Avoid using 64 bit types in Jason and `medea-client-api-proto`.
- Created PR:
=> Omit using 64-bit integer types in Jason and Client API

jason/CHANGELOG.md, jason/demo/index.html, jason/e2e-demo/js/index.js, jason/src/api/connection.rs, jason/src/api/mod.rs, jason/src/api/room.rs, jason/src/utils/callback.rs, jason/src/utils/mod.rs, jason/tests/api/connection.rs, jason/tests/api/mod.rs
Related to #27
В данный момент клиент не знает когда отваливается его Connection с удаленным Member'ом. Например:
1. Сценарий 1к1
2. Один из пользователей отключается
3. Второму пользователю мы отправляем `PeersRemoved` event, но клиентское приложение никак не узанет что коннекшен закрыт.
Add `ConnectionHandle.on_close` callback.
- Created PR:
=> Add ConnectionHandle.on_close callback (#27)

Makefile, jason/src/peer/mod.rs, src/media/peer.rs
Rust 1.45 is stable.
Upgrade to Rust 1.45.
- Created PR:
=> Upgrade stable Rust to 1.45 version 

Cargo.lock, Cargo.toml, src/api/client/session.rs
В один прекрасный день, в логах medea были обнаружены следующие вхождения:
```
12:29:45.396274947 WsSession [9] of Member [some_room/some_member]: Unsupported client message
12:29:45.396321317 WsSession [9] of Member [some_room/some_member]: Unsupported client message
...
12:29:50.748367698 WsSession [9] of Member [some_room/some_member]: Unsupported client message
12:29:51.192568323 WsSession [9] of Member [some_room/some_member]: Unsupported client message
```
Вылетает оно [тут](https://github.com/instrumentisto/medea/blob/8725316fa2a57613a3fd7ac99560338da3b27171/src/api/client/session.rs#L363).
Какие варианты там не обрабатываются:
1. `Binary`, `Ping`, `Pong` - по идее, им взяться неоткуда.
2. `Nop` - декодер этот вариант не возвращает.
3. `Continuation` - скорее всего оно.
Подробнее …
=> Handle fragmented WebSocket frames

Cargo.lock, proto/client-api/src/lib.rs, src/api/client/rpc_connection.rs, src/api/client/session.rs, src/api/mod.rs, src/media/mod.rs, src/media/peer.rs, src/signalling/participants.rs, src/signalling/peers/mod.rs, src/signalling/room/command_handler.rs, src/signalling/room/mod.rs, src/signalling/room/peer_events_handler.rs, src/signalling/room/rpc_server.rs, tests/e2e/signalling/add_endpoints_synchronization.rs, tests/e2e/signalling/mod.rs, tests/e2e/signalling/track_disable.rs
Part of #27
В комнате есть пользователь `Alice` у которого проблемное соединение с сервером, пользователь `Bob` отправляет больше одного `UpdateTracks` подряд для своего пира, соединенного с `Alice`. Пока renegotiation для первого `UpdateTracks` не завершится, пользователь `Bob` не получит `TracksApplied` для второго `UpdateTracks`. Это приводит к полному зависанию мьюта у `Bob`'а, пока `Alice` не восстановит подключение с сервером, поскольку `Alice` не может завершить renegotiation.
Отправлять `TracksApplied` без renegotiation, если пир на данный момент не Stable, и проводить новый renegotiation для этих изменений, когда пир перейдет в Stable стейт.
`TracksApplied` без renegotiation'а будут отправляться только на ивентов, которые требуют как можно более быстрого отрабатывания и могут …
=> Apply changes to remote Peer regardless of Peer state (#27)

mock/control-api/README.md, mock/control-api/src/api/ws.rs
Implement WebSocket broadcast in medea-control-api-mock
- Created PR:
=> Implement WebSocket broadcast in medea-control-api-mock

.clippy.toml, Cargo.lock, jason/CHANGELOG.md, jason/demo/index.html, jason/e2e-demo/js/index.js, jason/src/lib.rs, jason/src/media/constraints.rs, jason/src/media/mod.rs
Part of #27
We need to configure exact or ideal [`MediaTrackConstraints.facingMode`] constrain.
Add [`MediaTrackConstraints.facingMode`] configuring to the `DeviceVideoTrackConstraints`.
- Created PR:
[`MediaTrackConstraints.facingMode`]: https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/facingMode
=> Add facingMode constraint configuration to Jason (#27)

jason/src/api/mod.rs, jason/src/rpc/mod.rs, jason/tests/api/mod.rs
Part of #27
After `RpcClient`was refactored to `async_trait` usage in #135, `RpcClient::on_normal_close` starts require one more reference to the `RpcClient`. Because of it, `RpcClient` remains alive after `Room` close.
1. Return `LocalBoxFuture` from the `RpcClient::on_normal_close` instead of `async fn` usage
2. Add unit tests for this bug
- Created PR:
=> Fix RpcClient reference leak in Jason (#27)

Cargo.lock, src/api/control/grpc/server.rs
Refactor ControlApiService to more idiomatic async/.await
- Created PR:
=> Refactor ControlApiService to more idiomatic async/.await

Cargo.lock, jason/CHANGELOG.md, jason/src/media/constraints.rs, jason/src/media/manager.rs, jason/src/media/mod.rs, jason/src/media/track.rs, jason/src/peer/media/mod.rs, jason/src/peer/media/receiver.rs, jason/src/peer/tracks_request.rs, jason/tests/api/room.rs, jason/tests/media/constraints.rs, jason/tests/media/manager.rs, jason/tests/peer/mod.rs, jason/tests/web.rs, proto/client-api/CHANGELOG.md, proto/client-api/src/lib.rs, proto/client-api/src/stats.rs, src/media/peer.rs
Part of #27
Required for #144
Currently, in `MediaStreamSettings` can be specified only one type of video, but in #144 we need to simultaneous specify device and display video constraints.
Refactor Jason to constrain device and display video simultaneous.
- Created PR:
=> Improve Jason media constraints to support multiple video tracks (#27)

Cargo.lock, jason/CHANGELOG.md, jason/demo/index.html, jason/e2e-demo/js/index.js, jason/src/api/room.rs, jason/src/media/constraints.rs, jason/src/media/device_info.rs, jason/src/media/mod.rs, jason/src/media/track.rs, jason/src/peer/conn.rs, jason/src/peer/media/mod.rs, jason/src/peer/media/receiver.rs, jason/src/peer/media/sender.rs, jason/src/peer/mod.rs, jason/src/peer/tracks_request.rs, jason/tests/api/connection.rs, jason/tests/api/room.rs, jason/tests/media/constraints.rs, jason/tests/media/manager.rs, jason/tests/peer/mod.rs, jason/tests/web.rs
Как-то так повелось, что enum'ы в js'ку мы возвращаем в виде строк, так как решили что для js'ки так будет более идиоматично. При этом в функциях которые принимают enum'ы, мы принимаем enum'ы. Хочется достичь консистентности: мы или и принимаем и возвращаем enum'ы, или мы и принимаем и возвращаем стринги. 
Склоняюсь к первому варианту.
1. Expose `MediaKind` and `MediaSourceKind` enums. 
2. Change some exported functions return types:
`InputDeviceInfo.kind -> String => InputDeviceInfo.kind -> MediaKind`
`MediaTrack.kind -> String => MediaTrack.kind -> MediaKind`
`MediaTrack.media_source_kind -> String => MediaTrack.media_source_kind -> MediaSourceKind`
3. Internally we use 3 enums with `Audio` and `Video` variants: `InputDeviceKind`, `TransceiverKind` and `MediaTrackKind`. Get rid of those …
=> Return enums instead of strings in Jason's exported functions 

Cargo.lock, Makefile, crates/medea-coturn-telnet-client/src/lib.rs, crates/medea-macro/src/dispatchable.rs, crates/medea-macro/src/enum_delegate.rs, crates/medea-reactive/src/lib.rs, jason/src/peer/mod.rs, jason/src/rpc/websocket.rs, mock/control-api/src/api/mod.rs, src/api/client/session.rs, src/api/control/refs/local_uri.rs, src/signalling/participants.rs, src/signalling/room_service.rs, tests/e2e/grpc_control_api/create.rs
[Rust 1.47 is out](https://blog.rust-lang.org/2020/10/08/Rust-1.47.html)
Upgrade Rust to 1.47, fix new clippy lints.
- Created PR:
=> Upgrade stable Rust to 1.47 version

proto/client-api/src/lib.rs, src/api/client/session.rs
Part of #27
Required for #147
In #147 we extend `SeverMsg` and `ClientMsg` structs and custom (de)serializers starts to be complicated, so it was decided to start using `#[derive(Serialize, Deserialize)]`.
```json
{
"idle_timeout_ms": 10000,
"ping_interval_ms": 3000
}
```
```json
{
"msg": "RpcSettings",
"data": {
"idle_timeout_ms": 10000,
"ping_interval_ms": 3000
}
}
```
```json
{
"ping": 0
}
```
```json
{
"msg": "Ping",
"data": 0
}
```
```json
{
"event": "ConnectionQualityUpdated",
"data": {
"partner_member_id": "Velda",
"quality_score": "High"
}
}
```
```json
{
"msg": "Event",
"data": {
"event": "ConnectionQualityUpdated",
"data": {
"partner_member_id": "Henri",
"quality_score": "High"
}
}
}
```
Remove `Serialize` and `Deserialize` implementations for the `ServerMsg` and `ClientMsg`. …
=> Derive (de)serialization in medea-client-api-proto (#27)

proto/client-api/CHANGELOG.md, proto/client-api/src/lib.rs, src/api/client/rpc_connection.rs, src/api/client/server.rs, src/api/client/session.rs, src/api/control/member.rs, src/api/control/mod.rs, src/api/control/refs/fid.rs, src/api/control/refs/local_uri.rs, src/api/control/refs/mod.rs, src/api/control/refs/src_uri.rs, src/api/control/room.rs, src/media/ice_user.rs, src/signalling/elements/member.rs, src/signalling/participants.rs, src/signalling/peers/metrics/flowing_detector.rs, src/signalling/peers/metrics/mod.rs, src/signalling/peers/mod.rs, src/signalling/peers/traffic_watcher.rs, src/signalling/room/mod.rs, src/signalling/room/rpc_server.rs, src/signalling/room_repo.rs, src/signalling/room_service.rs, src/turn/allocation_event.rs, src/turn/mod.rs, src/turn/service.rs
Part of #27
Required for #147
In #147 we need to use `RoomId` and `Credentials` on the Jason side, so it was decided to move this newtypes from `medea` crate to the `medea-client-api-proto`.
Move `RoomId` to the `medea-client-api-proto` and use this newtype instead of old newtype.
Add `Credentials` newtype to the `medea-client-api-proto` and use it.
- Created PR:
=> Move RoomId and Credentials to the 'medea-client-api-proto' crate (#27)

jason/src/peer/media/mod.rs, jason/src/peer/mod.rs, jason/tests/api/room.rs, jason/tests/peer/mod.rs, jason/tests/web.rs, proto/client-api/src/lib.rs
Related to #144
Tests tests for the device/display muting/unmuting.
- Created PR:
=> Extend muting and unmuting send video test (#27)

CHANGELOG.md, Cargo.lock, proto/client-api/src/lib.rs, src/api/client/rpc_connection.rs, src/api/client/session.rs, src/api/control/callback/clients/grpc.rs, src/api/control/callback/clients/mod.rs, src/api/control/callback/mod.rs, src/api/control/callback/service.rs, src/api/control/callback/url.rs, src/api/control/error_codes.rs, src/signalling/participants.rs, src/signalling/room/dynamic_api.rs, src/signalling/room/mod.rs, src/signalling/room/rpc_server.rs, src/utils/mod.rs
В данный момент все коллбеки стреляют по принципу fire and forget. Для OnLeave это приемлимое поведение, но в случае с OnJoin будет правильнее ожидать ответа, таким образом CallbackServer получит возможность контроллировать процесс подключения пользователя к комнате.
- Created PR:
=> Wait for OnJoin callback result when accepting RpcConnection

crates/medea-reactive/src/collections/hash_map.rs, crates/medea-reactive/src/collections/hash_set.rs, crates/medea-reactive/src/collections/vec.rs, crates/medea-reactive/src/field/mod.rs, crates/medea-reactive/src/field/progressable_cell.rs, crates/medea-reactive/src/subscribers_store/progressable/mod.rs, crates/medea-reactive/src/subscribers_store/progressable/processed.rs, jason/src/peer/component.rs, jason/src/peer/media/receiver/component.rs, jason/src/peer/media/sender/component.rs, src/api/control/callback/clients/mod.rs, src/shutdown.rs, src/signalling/room/mod.rs, src/signalling/room/rpc_server.rs, src/turn/coturn_metrics.rs
Minor refactor to wider default type parameters usage to lower unnecessary verbosity.
- Created PR:
=> Refactor with wider type parameter defaults usage

Cargo.lock, jason/src/media/manager.rs
Related to #161
В #161 были добавлены две проверки состояния треков после их получения:
1. `ready_state == Live`.
2. `muted == false`.
`muted == false` - редкое, но валидное состояние для новых треков.
Откатить `muted == false` проверку.
- Created PR:
=> Remove !muted check on media tracks after getUserMedia()/getDisplayMedia() (#27)

Cargo.lock, jason/Cargo.toml, jason/src/media/constraints.rs, jason/src/media/manager.rs
Part of #27
Currently we're making [gDM] requests by inlined JS code, because until this moment [`web_sys`] haven't bindings for it. But in `0.3.47` version they was added. So now we should use [`web_sys`] bindings instead.
Remove `get_display_media` function from `medea_jason::media::manager` and use [`web_sys`] bindings instead.
- Created PR:
[gDM]: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia
[`web_sys`]: https://crates.io/crates/web-sys
=> Use getDisplayMedia() and DisplayMediaStreamConstraints from 'web_sys' crate (#27)

.rustfmt.toml, Cargo.lock, Makefile, crates/medea-macro/src/js_caused.rs, jason/src/peer/tracks_request.rs, mock/control-api/Cargo.toml, mock/control-api/src/api/mod.rs, proto/control-api/build.rs, src/api/control/refs/fid.rs, src/api/control/refs/local_uri.rs, src/utils/actix_try_join_all.rs
Rust v1.50 was [released], so we need to upgrade it.
- Created PR:
[released]: https://blog.rust-lang.org/2021/02/11/Rust-1.50.0.html
=> Upgrade stable Rust to 1.50 version

CHANGELOG.md, Cargo.lock, Cargo.toml, docs/rfc/0002-webrtc-client-api.md, jason/CHANGELOG.md, jason/Cargo.toml, jason/src/api/room.rs, jason/tests/api/room.rs, proto/client-api/CHANGELOG.md, proto/client-api/src/lib.rs, src/media/peer.rs, src/signalling/peers/mod.rs, src/signalling/room/command_handler.rs, src/signalling/room/mod.rs, src/signalling/room/peer_events_handler.rs, tests/integration/grpc_control_api/create.rs, tests/integration/signalling/add_endpoints_synchronization.rs, tests/integration/signalling/ice_restart.rs, tests/integration/signalling/mod.rs, tests/integration/signalling/track_disable.rs, tests/integration/signalling/track_mute.rs
Part of #27
#138 changes purpose of `Event::TracksApplied` and related objects. Now this objects are used for `Peer` updating instead of `Track`.
Rename `Event::TracksApplied` to `PeerUpdated` and all related objects.
- Created PR:
=> Rename Event::TracksUpdated to Event::PeerUpdated (#27)

jason/flutter/example/integration_test/jason.dart, jason/flutter/example/pubspec.lock, jason/flutter/lib/device_video_track_constraints.dart, jason/flutter/lib/ffi/completer.dart, jason/flutter/lib/ffi/exceptions.dart, jason/flutter/lib/ffi/foreign_value.dart, jason/flutter/lib/ffi/result.dart, jason/flutter/lib/ffi/unbox_handle.dart, jason/flutter/lib/jason.dart, jason/src/api/dart/device_video_track_constraints.rs, jason/src/api/dart/media_manager_handle.rs, jason/src/api/dart/mod.rs, jason/src/api/dart/reconnect_handle.rs, jason/src/api/dart/room_handle.rs, jason/src/api/dart/utils/err.rs, jason/src/api/dart/utils/errs.rs, jason/src/api/dart/utils/mod.rs, jason/src/api/dart/utils/result.rs, jason/src/api/wasm/reconnect_handle.rs, jason/src/platform/dart/utils/completer.rs, jason/src/rpc/backoff_delayer.rs, jason/src/rpc/reconnect_handle.rs
Пора уже думать как прокидывать ошибки из раста в дарт. 
Понятно что будем в дарте делать throw. По самим ошибкам хочется уйти от какого-то `JasonError` в котором в `name` и `message` стрингами лежат конкретные растовские ошибки, ибо такой вариант не шибко future proof. Думаю, тут следует провести категоризацию растовских ошибок, и выкидывать уже что-то более конкретное. По возможности используя ошибки из дартовского стд.
В этом PR'е идет базовая реализация всего этого механизма, ошибки в extern функциях пока по прежнему анврапятся, этот момент подьедет в следующем PR'е.
Про валидацию аргументов. В данный момент дарту без разницы на тип целочисленных значений. Т.е. в Uint8 можно прокинуть -1, а там просто произойдет каст с оверфловом. В этом PR'е все целочисленные типы (кроме случаев с …
=> Basic Rust to Dart error propagation and extern functions integer arguments validation

Cargo.lock, jason/flutter/example/integration_test/jason.dart, jason/flutter/example/pubspec.lock, jason/flutter/lib/connection_handle.dart, jason/flutter/lib/ffi/exceptions.dart, jason/flutter/lib/media_manager.dart, jason/flutter/lib/reconnect_handle.dart, jason/flutter/lib/room_handle.dart, jason/src/api/dart/connection_handle.rs, jason/src/api/dart/media_manager_handle.rs, jason/src/api/dart/mod.rs, jason/src/api/dart/reconnect_handle.rs, jason/src/api/dart/room_handle.rs, jason/src/api/dart/utils/err.rs, jason/src/api/dart/utils/mod.rs, jason/src/media/manager.rs, jason/src/peer/component/mod.rs, jason/src/peer/media/mod.rs, jason/src/peer/media/sender/component.rs, jason/src/platform/dart/error.rs, jason/src/platform/dart/media_devices.rs, jason/src/platform/wasm/media_devices.rs, jason/src/room.rs, jason/tests/peer/mod.rs
Продолжаем #204 расширяя список прокидываемых через FFI ошибок.
1. Растовские `HandlerDetached` ошибки теперь прокидываются как дартовский стдшный `StateError`
2. Растовские `MediaManagerError`'ы теперь прокидываются как дартовский `MediaManagerException`.
Плюс небольшой рефакторинг футур Раст => Dart, а именно, обертка c тайп-параметром. 
- Created PR:
=> Extend Rust to Dart error propagation

.github/workflows/ci.yml, mock/control-api/src/api/endpoint.rs, tests/e2e/features/media_mute.feature, tests/e2e/object/room.rs, tests/e2e/object/tracks_store.rs, tests/e2e/steps/track.rs, tests/e2e/world/member.rs, tests/e2e/world/mod.rs
В #206 было обнаружено что e2e тесты синхронихации состояний на самом деле синхронизацию состояний не тестировали, в процесс внесения исправлений в паре место пришлось поубирать различного рода ожидания. Это привело к снижению стабильности работы других e2e тестов, надо чинить.
- Created PR:
=> Fix flaky E2E tests
